--1.-CONSULTA:LA INFORMACIÓN DE LOS EMPLEADOS
SELECT 
	A.RUT_EP					AS 'RUT',
	A.NOM_EP					AS 'NOMBRE',
	A.APE_EP					AS 'APELLIDO',
	A.SUELDO_EP					AS 'SUELDO',
	A.FONO_EP					AS 'TELEFONO',
	A.DIRECC_EP					AS 'DIRECCION'
FROM 
	EMPLEADO					AS A;
 

--2.a.-CONSULTA:LAS HORAS TRABAJADAS EN UN DIA DE UN EMPLEADO Y SU SUELDO DEPENDIENDO DE LAS HORAS
SELECT 					--SUELDO EN UN DÍA
	A.RUT_EP														AS 'RUT',
	A.NOM_EP														AS 'NOMBRE',
	A.APE_EP														AS 'APELLIDO',
(datepart(HOUR,B.HO_SA_HO)-datepart(HOUR,B.HO_EN_HO))				AS 'HORAS TRABAJADAS', 
((datepart(HOUR,B.HO_SA_HO)-datepart(HOUR,B.HO_EN_HO))*A.SUELDO_EP) AS 'SUELDO', 
B.FE_TB_HO		 													AS 'FECHA DE TRABAJO'
FROM
	EMPLEADO A,
	HORARIO B
WHERE
 B.RUT_EP = A.RUT_EP AND
 A.RUT_EP = X AND
 B.FE_TB_HO= 'Y'  
-- ‘X (int)’ ES EL RUT DE LA PERSONA            QUE SE DESEA CONOCER EL SUELDO E ‘Y (date: 'yyyy-mm-dd')’ EL DIA DEL QUE SE DESEA CONOCER EL SUELDO
;

--2.b-CONSULTA:LAS HORAS TRABAJADAS EN UN MES DE UN EMPLEADO Y SU SUELDO DEPENDIENDO DE LAS HORAS
SELECT 					--SUELDO EN UN MES
	A.RUT_EP						AS 'RUT',
	A.NOM_EP						AS 'NOMBRE',
	A.APE_EP						AS 'APELLIDO',
	MONTH(B.FE_TB_HO)				AS 'MES',
SUM((datepart(HOUR,B.HO_SA_HO)-datepart(HOUR,B.HO_EN_HO)))				AS 'HORAS TRABAJADAS', 
(SUM(datepart(HOUR,B.HO_SA_HO)-datepart(HOUR,B.HO_EN_HO))*A.SUELDO_EP)	AS 'SUELDO'
FROM
	EMPLEADO A,
	HORARIO B
WHERE
 B.RUT_EP = A.RUT_EP AND
 A.RUT_EP = X AND   			-- ‘X (INT)’ EL RUT DE LA PERSONA QUE SE DESEA SABER EL SUELDO
 MONTH(B.FE_TB_HO) = Y AND		-- ‘Y (INT)’ EL MES DEL QUE SE DESEA SABER EL SUELDO DE LA PERSONA
 YEAR(B.FE_TB_HO) = Z			-- ‘Z (INT)’ EL AÑO DEL QUE SE DESEA SABER EL SUELDO DE LA PERSONA
GROUP BY
 A.RUT_EP,
 A.NOM_EP,
 A.APE_EP,
 MONTH(B.FE_TB_HO),
 A.SUELDO_EP;

--3.-CONSULTA:HORARIO DE UN EMPLEADO 
SELECT
    HO_EN_HO AS 'Entrada',
    HO_SA_HO AS 'Salida',
    FE_TB_HO AS 'Fecha' /* HORARIO A MOSTRAR DEL EMPLEADO QUE SE CONSULTA*/
FROM
    HORARIO
WHERE
    RUT_EP = X
    --SE CAMBIARA X(INT) DEPENDIENDO DEL RUT DEL EMPLEADO EL CUAL SE BUSCA EL HORARIO
ORDER BY Fecha;

--4.-CONSULTA: INFORMACIÓN DE UN PRODUCTO EN FUNCIÓN DE SU CÓDIGO DE BARRA
SELECT 
A.COD_BR_PD				AS 'CODIGO',
C.NOM_CF				AS 'CLASIFICACIÓN',
A.NOM_PD				AS 'NOMBRE',
A.PRECIO_PD				AS 'PRECIO',
A.CANT_CRIT_PD			AS 'STOCK'


FROM
	PRODUCTO A,
	CLASIFICACIÓN C
WHERE
	A.ID_CF = C.ID_CF AND
	A.COD_BR_PD = X     --’X (INT)’ EL CODIGO DE BARRA DEL PRODUCTO QUE SE DESEA SABER LA INFORMACIÓN
;

--5.a.-CONSULTA:PRODUCTOS VENDIDOS POR UN CIERTO EMPLEADO, ADEMÁS DE LA FECHA Y HORA EN LA QUE SE VENDIÓ EL PRODUCTO(POR NOMBRE)
SELECT
	A.RUT_EP				AS 'RUT',
	A.NOM_EP				AS 'NOMBRE',
	A.APE_EP				AS 'APELLIDO',
	B.COD_BR_PD				AS 'CODIGO PRODUCTO',
	B.NOM_PD				AS 'NOMBRE PRODUCTO',
	C.ID_RV					AS 'ID VENTA',
	C.CANT_RV				AS 'CANTIDAD DE VENTA',
	D.ID_VENTA				AS 'CODIGO VENTA',
	D.FECHA_VT				AS 'FECHA DE VENTA',
	D.HORA_VT				AS 'HORA DE VENTA'
FROM
	EMPLEADO A,
	PRODUCTO B,
	REG_VENTA C,
	VENTA D
WHERE
	A.RUT_EP = D.RUT_EP AND
C.COD_BR_PD = B.COD_BR_PD AND
C.ID_VENTA = D.ID_VENTA AND
A.NOM_EP = 'X'     			
-- ‘X (STRING)’ EL NOMBRE DEL EMPLEADO DEL QUE SE DESEA SABER LOS PRODUCTOS QUE HA VENDIDO
;

--5.b.-CONSULTA:PRODUCTOS VENDIDOS POR UN CIERTO EMPLEADO, ADEMÁS DE LA FECHA Y HORA EN LA QUE SE VENDIÓ EL PRODUCTO (POR RUT)

SELECT
	A.RUT_EP				AS 'RUT',
	A.NOM_EP				AS 'NOMBRE',
	A.APE_EP				AS 'APELLIDO',
	B.COD_BR_PD				AS 'CODIGO PRODUCTO',
	B.NOM_PD				AS 'NOMBRE PRODUCTO',
	C.ID_RV					AS 'ID VENTA',
	C.CANT_RV				AS 'CANTIDAD DE VENTA',
	D.ID_VENTA				AS 'CODIGO VENTA',
	D.FECHA_VT				AS 'FECHA DE VENTA',
	D.HORA_VT				AS 'HORA DE VENTA'
FROM
	EMPLEADO A,
	PRODUCTO B,
	REG_VENTA C,
	VENTA D
WHERE
	A.RUT_EP = D.RUT_EP AND
C.COD_BR_PD = B.COD_BR_PD AND
C.ID_VENTA = D.ID_VENTA AND
A.RUT_EP = X    			
-- ‘X (INT)’ EL NOMBRE DEL EMPLEADO DEL QUE SE DESEA SABER LOS PRODUCTOS QUE HA VENDIDO
;

--6.a.-CONSULTA:LOS PRODUCTOS ENTREGADOS POR CIERTO PROVEEDOR (POR RUT)
SELECT
	A.COD_BR_PD				AS 'CODIGO DE BARRAS',
B.CANTIDAD_RP 				AS 'CANTIDAD',
A.NOM_PD 					AS 'PRODUCTO'
FROM
 	PRODUCTO 				AS A,
REG_PROVISION 				AS B,
 	PROVISION 				AS C,
PROVEEDOR 					AS D

WHERE
    	A.COD_BR_PD = B.COD_BR_PD AND
    	B.ID_PV = C.ID_PV AND
    	C.RUT_PV = D.RUT_PV AND
    	D.RUT_PV = X 
--INGRESAR RUT EN X (INT)

ORDER BY
    	B.CANTIDAD_RP;

--6.b.-LOS PRODUCTOS ENTREGADOS POR CIERTO PROVEEDOR (POR NOMBRE)
SELECT
	A.COD_BR_PD				AS 'CODIGO DE BARRAS',
B.CANTIDAD_RP 				AS 'CANTIDAD',
A.NOM_PD 					AS 'PRODUCTO'
FROM
 	PRODUCTO 				AS A,
REG_PROVISION 				AS B,
 	PROVISION 				AS C,
PROVEEDOR 					AS D

WHERE
    	A.COD_BR_PD = B.COD_BR_PD AND
    	B.ID_PV = C.ID_PV AND
    	C.RUT_PV = D.RUT_PV AND
    	D.NOM_PV = 'X' 
--INGESAR NOMBRE EN X (STRING) 

ORDER BY
    	B.CANTIDAD_RP;


--7.a.-CONSULTA:INFORMACIÓN DE UN PRODUCTO(POR NOMBRE)

SELECT
	A.COD_BR_PD				AS 'CODIGO DE BARRAS',
    	A.NOM_PD 			AS 'NOMBRE DE PRODUCTO',
    	A.PRECIO_PD 		AS PRECIO,
    	A.CANT_CRIT_PD 		AS 'CANTIDAD CRITICA',
    	B.NOM_CF 			AS 'NOMBRE CLASIFICACION'
FROM
   	 PRODUCTO 				AS A,
    	 CLASIFICACION 		AS B
WHERE
	B.ID_CF = A.ID_CF AND
    	A.NOM_PD = 'X'
--INGRESAR EN X(string) EL NOMBRE DEL PRODUCTO
;

--7.b.-CONSULTA:INFORMACIÓN DE UN PRODUCTO(POR CÓDIGO DE BARRAS)
SELECT
	A.COD_BR_PD						AS 'CODIGO DE BARRAS',
    	A.NOM_PD 					AS 'NOMBRE DE PRODUCTO',
    	A.PRECIO_PD 				AS PRECIO,
    	A.CANT_CRIT_PD 				AS 'CANTIDAD CRITICA',
    	B.NOM_CF 					AS 'NOMBRE DE CLASIFICACION'
FROM
   	 PRODUCTO 						AS A,
    	 CLASIFICACION 				AS B
WHERE
	B.ID_CF = A.ID_CF AND
    	A.COD_BR_PD = X
--INGRESAR EN X(int) EL CÓDIGO DE BARRAS DEL PRODUCTO
;


--8.-CONSULTA: STOCK DE PRODUCTOS
SELECT
    A.NOM_PD   		AS 'Nombre',
    A.COD_BR_PD		AS 'Codigo',
    A.CANT_CRIT_PD 	AS 'Stock Critico',
    SUM(B.CANTIDAD_RP) 	AS 'Stock del Producto' 
/* MOSTRAR NOMBRE, CODIGO Y STOCK */
FROM
    PRODUCTO A,
    REG_PROVISION B
WHERE
    A.COD_BR_PD = B.COD_BR_PD
GROUP BY
	A.NOM_PD,
	A.COD_BR_PD,
	A.CANT_CRIT_PD
ORDER BY
    A.NOM_PD;
--9.-CONSULTA: LISTADO DE PRODUCTOS CON STOCK MENOR O IGUAL AL STOCK CRÍTICO

SELECT
	A.COD_BR_PD			AS 'CODIGO DE BARRAS',
	A.NOM_PD			AS 'PRODUCTO',
	B.NOM_CF			AS 'NOMBRE DE CLASIFICACION',
	SUM(C.CANTIDAD_RP)	AS 'CANTIDAD DEL PRODUCTO',
	A.CANT_CRIT_PD		AS 'CANTIDAD CRITICA'

FROM
	PRODUCTO			AS A,
	CLASIFICACION		AS B,
	REG_PROVISION		AS C
WHERE
	A.ID_CF = B.ID_CF AND A.COD_BR_PD = ID_RP
GROUP BY 
	A.COD_BR_PD,
	A.NOM_PD,
	B.NOM_CF,
	A.CANT_CRIT_PD
HAVING 
	SUM(C.CANTIDAD_RP)		<=		A.CANT_CRIT_PD
--10.-CONSULTA:LISTADO DE PRODUCTOS VENCIDOS
SELECT
    	A.COD_BR_PD 				AS 'CODIGO DE BARRAS',
    	A.NOM_PD 					AS 'PRODUCTO',
    	B.FECHA_VENCI_RP 			AS 'FECHA DE VENCIMIENTO'
    
FROM
    	PRODUCTO 					AS A,
    	REG_PROVISION 				AS B
WHERE
	A.COD_BR_PD = B.COD_BR_PD AND
	DATEDIFF(DAY, CONVERT(DATE,GETDATE()),B.FECHA_VENCI_RP) <0 
ORDER BY
    	A.COD_BR_PD;
--11.-CONSULTA: LISTADO DE PRODUCTOS POR VENCER
SELECT
    PRODUCTO.NOM_PD AS 'Nombre',
    DATEDIFF(day, CONVERT(date, GETDATE()), REG_PROVISION.FECHA_VENCI_RP)AS 'Dias restantes' 
	-- CALCULA LA DIFERENCIA EN DIAS ENTRA LA FECHA DE VENCIMIENTO Y LA DEL COMPUTADOR
FROM
    REG_PROVISION INNER JOIN PRODUCTO
    ON REG_PROVISION.COD_BR_PD = PRODUCTO.COD_BR_PD
WHERE   
	DATEDIFF(day,CONVERT(date,GETDATE()),REG_PROVISION.FECHA_VENCI_RP) <= X AND 
	DATEDIFF(day,CONVERT(date,GETDATE()),REG_PROVISION.FECHA_VENCI_RP) >0
    --SE CAMBIA X (int) DEPENDIENDO DE LOS DIAS MAXIMOS ESPERADOS ANTES DE LA FECHA DE VENCIMIENTO
ORDER BY 
	'Dias restantes';


--12-.CONSULTA: INFORMACIÓN DE PROVEEDORES CON DEUDA
SELECT
    PROVEEDOR.NOM_PV   		AS 'Nombre',
    PROVISION.DEUDA_PI 		AS 'Deuda',
    PROVISION.FECHA_MAX_PI	AS 'Fecha de paga'
FROM
    PROVEEDOR,
	PROVISION
WHERE
	PROVEEDOR.RUT_PV = PROVISION.RUT_PV AND
    PROVISION.DEUDA_PI > 0
ORDER BY
	Nombre;
	
--13.-CONSULTA: INFORMACIÓN DE TODOS LOS PROVEEDORES
SELECT
    	A.RUT_PV 					AS RUT,
    	A.NOM_PV 					AS NOMBRE,
    	A.APE_PV 					AS APELLIDO,
    	A.FONO_PV 					AS 'NUMERO DE CONTACTO',
    	A.EMPRESA_PV				AS 'NOMBRE DE EMPRESA'

FROM
   	 PROVEEDOR 						AS A
ORDER BY
	A.RUT_PV;

--14.a.-CONSULTA: LISTADO DE LAS VENTAS HECHAS EN UN CIERTO DIA
SELECT
	A.ID_VENTA				AS 'NUMERO DE BOLETA',
	D.RUT_EP				AS 'RUT CAJERO',
	D.NOM_EP+' '+D.APE_EP	AS 'NOMBRE DEL CAJERO',
	A.FECHA_VT				AS 'FECHA DE VENTA',
	A.HORA_VT				AS 'HORA DE VENTA',
	C.COD_BR_PD				AS 'CODIGO DE BARRAS',
	C.NOM_PD				AS 'PRODUCTO',
	SUM(B.CANT_RV)			AS 'CANTIDAD',
	SUM(C.PRECIO_PD*B.CANT_RV)	AS 'PRECIO TOTAL POR PRODUCTO'
FROM
	VENTA					AS A,
	REG_VENTA				AS B,
	PRODUCTO				AS C,
	EMPLEADO				AS D
WHERE
	A.ID_VENTA = B.ID_VENTA AND
	B.COD_BR_PD = C.COD_BR_PD AND
	D.RUT_EP = A.RUT_EP		AND
	A.FECHA_VT = 'Y' --REEMPLAZAR "Y" POR LA FECHA DESEADA "Y" (DATE) ('YYYY-MM-DD')
GROUP BY
	A.ID_VENTA, D.RUT_EP, D.NOM_EP, D.APE_EP, A.FECHA_VT,
A.HORA_VT, C.COD_BR_PD, C.NOM_PD
ORDER BY
	A.ID_VENTA;
--14.b.-CONSULTA: LISTADO DE LAS VENTAS HECHAS EN UN CIERTO MES
SELECT
	A.ID_VENTA					AS 'NUMERO DE BOLETA',
	D.RUT_EP					AS 'RUT CAJERO',
	D.NOM_EP+' '+D.APE_EP		AS 'NOMBRE DEL CAJERO',
	A.FECHA_VT					AS 'FECHA DE VENTA',
	A.HORA_VT					AS 'HORA DE VENTA',
	C.COD_BR_PD					AS 'CODIGO DE BARRAS',
	C.NOM_PD					AS 'PRODUCTO',
	SUM(B.CANT_RV)				AS 'CANTIDAD',
	SUM(C.PRECIO_PD*B.CANT_RV)	AS 'PRECIO TOTAL POR PRODUCTO'

FROM
	VENTA					AS A,
	REG_VENTA				AS B,
	PRODUCTO				AS C,
	EMPLEADO				AS D
WHERE
	A.ID_VENTA = B.ID_VENTA AND
	B.COD_BR_PD = C.COD_BR_PD AND
	D.RUT_EP = A.RUT_EP	AND
	--CONDICIONES SEGÚN LO REQUERIDO
	--MES
	MONTH(A.FECHA_VT) = Y	AND
	--AÑO
	YEAR(A.FECHA_VT) = Z
	--CAMBIAR Y (INT) ,Z (INT) SEGÚN EL VALOR DESEADO
GROUP BY
	A.ID_VENTA, D.RUT_EP, D.NOM_EP, D.APE_EP, A.FECHA_VT,
A.HORA_VT, C.COD_BR_PD, C.NOM_PD
ORDER BY
	A.ID_VENTA;
--14.c.-CONSULTA: LISTADO DE LAS VENTAS HECHAS EN UN CIERTO AÑO

SELECT
	A.ID_VENTA				AS 'NUMERO DE BOLETA',
	D.RUT_EP				AS 'RUT CAJERO',
	D.NOM_EP+' '+D.APE_EP	AS 'NOMBRE DEL CAJERO',
	A.FECHA_VT				AS 'FECHA DE VENTA',
	A.HORA_VT				AS 'HORA DE VENTA',
	C.COD_BR_PD				AS 'CODIGO DE BARRAS',
	C.NOM_PD				AS 'PRODUCTO',
	SUM(B.CANT_RV)			AS 'CANTIDAD',
	SUM(C.PRECIO_PD*B.CANT_RV)	AS 'PRECIO TOTAL POR PRODUCTO'

FROM
	VENTA					AS A,
	REG_VENTA				AS B,
	PRODUCTO				AS C,
	EMPLEADO				AS D
WHERE
	A.ID_VENTA = B.ID_VENTA AND
	B.COD_BR_PD = C.COD_BR_PD AND
	D.RUT_EP = A.RUT_EP		AND
	--CONDICIONES SEGÚN LO REQUERIDO
	--AÑO
	YEAR(A.FECHA_VT) = Z
	--CAMBIAR Z(INT) SEGÚN EL VALOR DESEADO
GROUP BY
	A.ID_VENTA, D.RUT_EP, D.NOM_EP, D.APE_EP, A.FECHA_VT,
A.HORA_VT, C.COD_BR_PD, C.NOM_PD
ORDER BY
	A.ID_VENTA;

--15.-CONSULTA: MOSTRAR PRODUCTOS SEGÚN SU CLASIFICACIÓN
SELECT
	A.NOM_CF					AS 'CLASIFICACION',
	B.COD_BR_PD					AS 'CODIGO DE BARRAS',
	B.NOM_PD					AS 'PRODUCTO'
FROM
	CLASIFICACION				AS A,
	PRODUCTO					AS B
WHERE
	A.ID_CF = B.ID_CF
ORDER BY
	A.NOM_CF;

--16.-CONSULTA: MOSTRAR TODOS LOS PRODUCTOS DE UNA CIERTA CLASIFICACIÓN
SELECT
	A.NOM_CF					AS 'CLASIFICACION',
	B.COD_BR_PD					AS 'CODIGO DE BARRAS',
	B.NOM_PD					AS 'PRODUCTO'
FROM
	CLASIFICACION				AS A,
	PRODUCTO					AS B
WHERE
	A.ID_CF = B.ID_CF			AND
	A.NOM_CF = 'X' 
--REEMPLAZAR X (STRING) POR LA CLASIFICACIÓN DESEADA
ORDER BY
	B.COD_BR_PD;
