INSERT INTO VENTA VALUES (19888999, (SELECT CONVERT(VARCHAR(8), GETDATE(), 112) AS [YYYYMMDD]), (SELECT CONVERT(TIME, GETDATE())))
SELECT * FROM PRODUCTO where COD_BR_PD=(select max(COD_BR_PD) from PRODUCTO)
SELECT MAX(ID_VENTA) from VENTA
SELECT * FROM VENTA

SELECT * FROM REG_VENTA
SELECT * FROM VENTA
INSERT INTO REG_VENTA VALUES (ID, CODPROD, CANNTIDAD)

SELECT * FROM REG_PROVISION
SELECT * FROM PROVISION